# Generated by Django 5.0.6 on 2024-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tcc_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='code',
        ),
        migrations.AddField(
            model_name='tcc',
            name='qrcode',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
