# Generated by Django 5.0.6 on 2024-07-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_tcc_code_tcc_qrcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcc',
            table=None,
        ),
    ]
