# Generated by Django 5.0.6 on 2024-07-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_tcc_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcc',
            table='tcc',
        ),
    ]
