# Generated by Django 5.0.6 on 2024-07-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_tcc_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tcc',
            table=None,
        ),
    ]
