# Generated by Django 5.0.6 on 2024-07-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_tcc_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='qrcode',
        ),
    ]
