# Generated by Django 5.0.6 on 2024-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_tcc_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcc',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='postcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='qrcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='register_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tcc',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='tcc',
            table='tcc',
        ),
    ]
