# Generated by Django 5.0.6 on 2024-07-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_tcc_address_tcc_email_tcc_gender_tcc_name_tcc_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='qrcode',
            field=models.CharField(default='default_qr_code', max_length=255, null=True),
        ),
    ]
