# Generated by Django 5.0.6 on 2024-07-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_tcc_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='qrcode',
            field=models.CharField(default='default_qr_code', max_length=255),
        ),
    ]
