# Generated by Django 5.0.6 on 2024-07-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_tcc_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='id',
        ),
        migrations.AlterField(
            model_name='tcc',
            name='qrcode',
            field=models.CharField(default='default_qr_code', max_length=255, primary_key=True, serialize=False),
        ),
    ]
