# Generated by Django 5.0.6 on 2024-07-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_tcc_id_alter_tcc_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcc',
            old_name='address',
            new_name='adress',
        ),
    ]
