# Generated by Django 5.0.6 on 2024-07-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_address_tcc_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcc',
            old_name='register_date',
            new_name='registerdate',
        ),
    ]
